server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_loki]
        action: keep
        regex: "true"
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project
      - target_label: job
        replacement: containers
      # Добавим проверку на наличие метки и присвоим значение по умолчанию
      - target_label: container
        replacement: 'unknown'
        action: replace
        regex: '^$'
        source_labels: [container]
      - target_label: __path__
        replacement: /var/lib/docker/containers/*/*.log
